-- Seed data for companies table
USE codifyme;

INSERT INTO companies (name, logo_url, description, difficulty_level) VALUES
('Google', 'https://logo.clearbit.com/google.com', 'Leading technology company specializing in Internet-related services and products', 'Hard'),
('Microsoft', 'https://logo.clearbit.com/microsoft.com', 'Multinational technology corporation producing computer software, consumer electronics, and personal computers', 'Hard'),
('Amazon', 'https://logo.clearbit.com/amazon.com', 'American multinational technology company focusing on e-commerce, cloud computing, and AI', 'Hard'),
('Meta', 'https://logo.clearbit.com/meta.com', 'Technology conglomerate focusing on social media, virtual reality, and metaverse technologies', 'Hard'),
('Apple', 'https://logo.clearbit.com/apple.com', 'Technology company that designs, develops, and sells consumer electronics and software', 'Hard'),
('Netflix', 'https://logo.clearbit.com/netflix.com', 'Streaming entertainment service with original content production', 'Medium'),
('Adobe', 'https://logo.clearbit.com/adobe.com', 'Software company known for creative and multimedia software products', 'Medium'),
('Salesforce', 'https://logo.clearbit.com/salesforce.com', 'Cloud-based software company specializing in customer relationship management', 'Medium'),
('Oracle', 'https://logo.clearbit.com/oracle.com', 'Computer technology corporation specializing in database software and cloud solutions', 'Medium'),
('IBM', 'https://logo.clearbit.com/ibm.com', 'Technology and consulting company offering hardware, software, and cloud services', 'Medium'),
('Intel', 'https://logo.clearbit.com/intel.com', 'Technology company that manufactures semiconductor chips and related products', 'Medium'),
('Nvidia', 'https://logo.clearbit.com/nvidia.com', 'Technology company specializing in graphics processing units and AI computing', 'Hard'),
('Tesla', 'https://logo.clearbit.com/tesla.com', 'Electric vehicle and clean energy company with advanced software engineering', 'Hard'),
('Uber', 'https://logo.clearbit.com/uber.com', 'Ride-hailing and food delivery platform with complex distributed systems', 'Medium'),
('Airbnb', 'https://logo.clearbit.com/airbnb.com', 'Online marketplace for lodging and tourism experiences', 'Medium'),
('Spotify', 'https://logo.clearbit.com/spotify.com', 'Audio streaming and media services provider', 'Medium'),
('LinkedIn', 'https://logo.clearbit.com/linkedin.com', 'Professional networking platform and career development service', 'Medium'),
('Twitter', 'https://logo.clearbit.com/twitter.com', 'Social media platform for real-time information and communication', 'Medium'),
('Snap', 'https://logo.clearbit.com/snap.com', 'Camera and social media company known for Snapchat', 'Medium'),
('PayPal', 'https://logo.clearbit.com/paypal.com', 'Online payments system and financial technology company', 'Medium'),
('Stripe', 'https://logo.clearbit.com/stripe.com', 'Financial services and software company for online payment processing', 'Medium'),
('Shopify', 'https://logo.clearbit.com/shopify.com', 'E-commerce platform for online stores and retail point-of-sale systems', 'Easy'),
('Atlassian', 'https://logo.clearbit.com/atlassian.com', 'Software company developing products for software developers and project managers', 'Medium'),
('Slack', 'https://logo.clearbit.com/slack.com', 'Business communication platform offering chat and collaboration tools', 'Easy'),
('Zoom', 'https://logo.clearbit.com/zoom.us', 'Video communications company providing cloud-based peer-to-peer software', 'Easy'),
('Dropbox', 'https://logo.clearbit.com/dropbox.com', 'File hosting service offering cloud storage and file synchronization', 'Easy'),
('GitHub', 'https://logo.clearbit.com/github.com', 'Platform for version control and collaboration for software developers', 'Easy'),
('Reddit', 'https://logo.clearbit.com/reddit.com', 'Social news aggregation and discussion website', 'Medium'),
('Pinterest', 'https://logo.clearbit.com/pinterest.com', 'Image sharing and social media service for discovering ideas', 'Easy'),
('Twitch', 'https://logo.clearbit.com/twitch.tv', 'Live streaming platform focused on video game streaming and esports', 'Medium');
